# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PST', '0004_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='idQuestion',
            new_name='Question',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='idUser',
            new_name='User',
        ),
        migrations.AlterField(
            model_name='test',
            name='Question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PST.question'),
        ),
    ]
